
# Auto-generated by build_overlay.py -- edit that script, not this file.
.set STATE,      0x8049fe18
.set GETGOBJ,    0x80301fb4
.set CREATE,     0x80302834
.set SHOW,       0x80302810
.set HIDECURSOR, 0x80302ab0
.set SETBG,      0x80302b90
.set SETFG,      0x80302b64
.set SETSCALE,   0x80302b10
.set ERASE,      0x80302bb0
.set SETXY,      0x80302a3c
.set PRINTF,     0x80302d4c
.set DRAWLIST,   0x804d6e18
.set SELECTED,   0x804d49e8
.set MAP,        0x803e9960
.set LIVEID,     0x8049e750
.set SDTBL,      0x803dfedc
.set PAD,        0x804c20bc
.set PENDSC,     0x80479d35
.set ADVNOW,     0x80479d64

.macro CALL addr
    lis 12, \addr@h
    ori 12, 12, \addr@l
    mtctr 12
    bctrl
.endm

.text
.global hook_entry
hook_entry:
    # DevText_DrawAll(gobj r3, pass r4); only act on the draw pass, like it does
    cmplwi 4, 2
    bne orig_tail
    mflr 0
    stw 0, 4(1)
    stwu 1, -0x40(1)
    stw 3, 0x08(1)
    stw 4, 0x0C(1)
    stw 23, 0x14(1)
    stw 24, 0x18(1)
    stw 25, 0x1C(1)
    stw 26, 0x20(1)
    stw 27, 0x24(1)
    stw 28, 0x28(1)
    stw 29, 0x2C(1)
    stw 30, 0x30(1)
    stw 31, 0x34(1)
    bl main
    lwz 23, 0x14(1)
    lwz 24, 0x18(1)
    lwz 25, 0x1C(1)
    lwz 26, 0x20(1)
    lwz 27, 0x24(1)
    lwz 28, 0x28(1)
    lwz 29, 0x2C(1)
    lwz 30, 0x30(1)
    lwz 31, 0x34(1)
    lwz 3, 0x08(1)
    lwz 4, 0x0C(1)
    addi 1, 1, 0x40
    lwz 0, 4(1)
    mtlr 0
    b orig_tail

main:
    mflr 0
    stw 0, 4(1)
    stwu 1, -0x10(1)
    lis 31, STATE@h
    ori 31, 31, STATE@l
    CALL GETGOBJ                # devtext gobj for this scene
    cmplwi 3, 0
    beq done
    mr 30, 3
    # our DevText survives only until the next scene reset: trust it only if
    # it is still linked on devtext_drawlist
    lwz 29, 4(31)
    cmplwi 29, 0
    beq create
    lis 5, DRAWLIST@h
    ori 5, 5, DRAWLIST@l
    lwz 5, 0(5)
walk:
    cmplwi 5, 0
    beq create
    cmpw 5, 29
    beq have_text
    lwz 5, 48(5)
    b walk
create:
    li 3, 9                     # id (game debug uses 1/7/8)
    li 4, 24                    # x
    li 5, 380                   # y (3 rows x 18px, above the bottom edge)
    li 6, 32
    li 7, 4
    addi 8, 31, -344
    CALL CREATE
    cmplwi 3, 0
    bne created
    li 0, 0
    stw 0, 4(31)
    b done
created:
    mr 29, 3
    stw 29, 4(31)
    mr 3, 30
    mr 4, 29
    CALL SHOW
    mr 3, 29
    CALL HIDECURSOR
    mr 3, 29
    addi 4, 31, 8
    CALL SETBG
    mr 3, 29
    addi 4, 31, 12
    CALL SETFG
    mr 3, 29
    lfs 1, 16(31)
    lfs 2, 20(31)
    CALL SETSCALE
have_text:
    mr 3, 29
    CALL ERASE
    mr 3, 29
    li 4, 0
    li 5, 0
    CALL SETXY
    # ext = selected_stage.external_id
    lis 5, SELECTED@h
    ori 5, 5, SELECTED@l
    lwz 28, 0(5)
    # map = stage_id_map[ext].internal_id, -1 if out of range
    li 27, -1
    cmplwi 28, 0x11d
    bgt got_map
    mulli 0, 28, 12
    lis 5, MAP@h
    ori 5, 5, MAP@l
    lwzx 27, 5, 0
got_map:
    # live = stage_info.internal_stage_id
    lis 5, LIVEID@h
    ori 5, 5, LIVEID@l
    lwz 26, 0(5)
    # live stage archive name via Ground_803DFEDC[live]->data1
    addi 25, 31, 100
    cmplwi 26, 0x6e
    bgt got_name
    lis 5, SDTBL@h
    ori 5, 5, SDTBL@l
    slwi 0, 26, 2
    lwzx 5, 5, 0
    cmplwi 5, 0
    beq got_name
    lwz 5, 8(5)
    cmplwi 5, 0
    beq got_name
    mr 25, 5
got_name:
    # ext enum name (0x00..0x20 only)
    addi 24, 31, 100
    cmplwi 28, 0x20
    bgt got_ext
    mulli 0, 28, 12
    addi 24, 31, 128
    add 24, 24, 0
got_ext:
    addi 23, 31, 96
    cmpw 27, 26
    beq judged
    addi 23, 31, 104
judged:
    mr 3, 29                    # "ext  0x07 CORNERIA"
    addi 4, 31, 24
    mr 5, 28
    mr 6, 24
    CALL PRINTF
    mr 3, 29                    # "int  0x0E (map 0x0E) OK"
    addi 4, 31, 64
    mr 5, 26
    mr 6, 27
    mr 7, 23
    CALL PRINTF
    mr 3, 29                    # "file GrCn.dat"
    addi 4, 31, 40
    mr 5, 25
    CALL PRINTF
    # fourth line: pending target, while it differs from current
    lwz 8, 0(31)
    cmplwi 8, 0
    beq no_line4
    cmpw 8, 28
    beq no_line4
    mr 3, 29
    addi 4, 31, 48
    mr 5, 8
    CALL PRINTF
no_line4:
    # buttons (mode >= 1): P1 D-pad Right/Left cycles the external stage id
    lwz 5, 116(31)
    cmplwi 5, 0
    beq done
    lis 5, PAD@h
    ori 5, 5, PAD@l
    lwz 6, 8(5)                 # HSD_PadCopyStatus[0].trigger
    andi. 7, 6, 0x100           # A: arm autoplay
    beq no_arm
    li 0, 1
    stw 0, -352(31)
no_arm:
    andi. 7, 6, 2               # D-pad Right: next
    bne adv_next
    andi. 7, 6, 1               # D-pad Left: prev
    bne adv_prev
    # autoplay: walk external ids without input, record results.
    # Runs always in mode 2 (headless autosweep); in mode 1 after A arms it.
    lwz 5, 116(31)
    cmplwi 5, 2
    beq sweep_go
    lwz 5, -352(31)
    cmplwi 5, 0
    beq done
sweep_go:
    lwz 5, -844(31)
    cmplwi 5, 0
    bne done
    lwz 8, 0(31)
    cmplwi 8, 0
    bne sweep_check
    mr 8, 28                    # adopt the current stage as first target
    stw 8, 0(31)
sweep_check:
    cmpw 8, 28                  # still waiting for a pending reload?
    bne sweep_wait
    cmplwi 26, 0                # and for an actually loaded stage
    bne sweep_stable
sweep_wait:
    li 0, 0
    stw 0, -840(31)
    lwz 9, -836(31)
    addi 9, 9, 1
    stw 9, -836(31)
    cmpwi 9, 60                 # scene stuck (e.g. CSS): poke the exit again
    blt done
    li 0, 0
    stw 0, -836(31)
    lwz 9, -348(31)
    addi 9, 9, 1
    stw 9, -348(31)
    cmpwi 9, 16                 # target never loads (the game short-circuits
    blt poke                    # same-stage reloads, e.g. 0x19->0x1A): skip it
    li 0, 0
    stw 0, -348(31)
    b adv_next
sweep_stable:
    lwz 9, -840(31)
    addi 9, 9, 1
    stw 9, -840(31)
    cmpwi 9, 90                 # ~1.5s on this stage: record and move on
    bne done
    lwz 10, -848(31)
    cmplwi 10, 39
    bgt done
    mulli 0, 10, 12
    addi 11, 31, -832
    add 11, 11, 0
    stw 28, 0(11)               # external id
    stw 27, 4(11)               # stage_id_map internal id
    stw 26, 8(11)               # live internal id
    addi 10, 10, 1
    stw 10, -848(31)
    li 0, 0
    stw 0, -840(31)
    cmplwi 28, 32        # single pass ends at the last VS external
    blt adv_next
    li 0, 1
    stw 0, -844(31)
    b done
adv_next:
    addi 5, 31, -84
    b adv_common
adv_prev:
    addi 5, 31, -48
adv_common:
    lwz 8, 0(31)
    cmplwi 8, 0
    bne 1f
    mr 8, 28
1:  cmplwi 8, 32
    bgt 2f
    lbzx 8, 5, 8                # order table: avoids same-stage reloads
    cmplwi 8, 2
    bge commit
2:  li 8, 2
commit:
    stw 8, 0(31)
    li 0, 0
    stw 0, -348(31)
poke:
    li 6, 3                     # force current minor scene to exit,
    lis 5, PENDSC@h             # fn_8016E730 will apply the pending id
    ori 5, 5, PENDSC@l
    stb 6, 0(5)
    li 6, 1
    lis 5, ADVNOW@h
    ori 5, 5, ADVNOW@l
    stw 6, 0(5)
done:
    addi 1, 1, 0x10
    lwz 0, 4(1)
    mtlr 0
    blr

orig_tail:
    mflr 0                      # displaced DevText_DrawAll first instruction
    b DRAWALL_RET               # resolved by ld (stripped for the Gecko C2 variant)
